<?php

        $msg = '';

		echo "$msg"; 

?>
       <table border='0' class='tbl'>
 				
                <tr>
                        <td><b>Icons</b></td>
                        <td><b>&nbsp;&nbsp; Meaning &nbsp;&nbsp;</b></td>
                        <td><b>Description &nbsp;</b></td>
                </tr>
                <tr>
                        <td colspan=3><br><hr></td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_help.gif></td>
                        <td>Help</td><td>shows help about feature</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_info.gif></td>
                        <td>Info</td><td>shows info about feature</td>
                </tr>                
                <tr>
                        <td align='center'><img src=gfx/ico_stop.gif></td>
                        <td>Stop</td><td>operation was aborted</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_no.gif></td>
                        <td>No</td><td>operation denied</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_yes.gif></td>
                        <td>Yes</td><td>operation accepted</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_warn.gif></td>
                        <td>Warning</td><td>notifies of error</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_notice.gif></td>
                        <td>Notice</td><td>notifies of possible issue</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_on.gif></td>
                        <td>On</td><td>status/feature is ok/enabled</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_off.gif></td>
                        <td>Off</td><td>status/feature is not ok/disabled</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_re.gif></td>
                        <td>Reload</td><td>generic reload icon</td>
                </tr>                
                <tr>
                        <td align='center'><img src=gfx/ico_delete.gif></td>
                        <td>Delete</td><td>generic delete icon</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_create.gif></td>
                        <td>Create</td><td>generic add icon</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_edit.gif></td>
                        <td>Edit</td><td>generic edit icon</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_properties.gif></td>
                        <td>Properties</td><td>generic manage icon</td>
                </tr> 
                <tr>
                        <td align='center'><img src=gfx/ico_check.gif></td>
                        <td>Check</td><td>generic OK</td>
                </tr>              
                <tr>
                        <td align='center'><img src=gfx/ico_mail.gif></td>
                        <td>Mail</td><td>generic mail icon</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_catch.gif></td>
                        <td>Catch-all</td><td>catch-all account</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_postmaster.gif></td>
                        <td>Postmaster</td><td>postmaster account</td>
                </tr>                
                <tr>
                        <td align='center'><img src=gfx/ico_user.gif></td>
                        <td>User</td><td>generic user icon</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_user_new.gif></td>
                        <td>New User</td><td>create new user</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_list.gif></td>
                        <td>Maillist</td><td>generic mailing list</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_list_new.gif></td>
                        <td>New Maillist</td><td>create new mailing list</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_filter_on.gif></td>
                        <td>Filters</td><td>on-line filter icon</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_filter_off.gif></td>
                        <td>Filters</td><td>off-line filter icon</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_log.gif></td>
                        <td>Logs</td><td>generic log icon</td>
                </tr>
                <tr>
                        <td align='center'><img src=gfx/ico_see.gif></td>
                        <td>Text</td><td>generic see icon</td>
                </tr>
                <tr>
                        <td colspan=3><br><hr></td>
                </tr>
        </table>
</form>
<br><br>